### ISSUE TITLE
Just use Github Issues and not Mailing List

### ISSUE THREAD

**Issue by skreutzberger** [akolov/swift-logging#3]
Hi,

I know that mailing lists are an established way of discussing stuff for programming languages but maybe can just use the Github Issues section of the repo? 

It is much easier to read and write stuff and it is already grouped by topic. Using labels you can add even more context to a discussion and since everyone is anyway using Github we can leverage Github’s notification system :)

What do you think?

P.S.: Thanks for initiating that discussion in the first place. Logging is fundamental to every programming language and having a great, simple solution will be key for all the new developers coming from other programming languages to the hot and newly open-sourced Swift 2 :smile:  

Sebastian

**Comment by sashka** [comment]
+1 to GitHub issues.

**Comment by akolov** [comment]
Works for me if everyone else agrees, what do you think @emaloney?

**Comment by roshanrags** [comment]
:+1:

**Comment by spoof** [comment]
:+1:

**Comment by emaloney** [comment]
Fine by me.

**Comment by emaloney** [comment]
We should update the Contributing section of the README to remove the mailing list reference & to reflect how we'd like people to communicate with us.

**Comment by akolov** [comment]
Could someone please edit README and make a pull request or just merge it directly?

**Comment by emaloney** [comment]
I've created a pull request with a first attempt at describing a workflow.

Comments welcome!

**Comment by emaloney** [comment]
Once we've merged this (or something like this) in, we should send a note to the mailing list letting people know it's being decommissioned.
