### ISSUE TITLE
Proposal: Rename repository to swift-logging-specifications

### ISSUE THREAD

**Issue by emaloney** [akolov/swift-logging#5]
Cloning this repo results in a directory called `specifications` while forking it leaves me with a personal copy of a repo called `specifications`.

I keep all of my cloned repos in a single directory, and it always takes me a couple beats to remember what the `specifications` directory is about. Same when I see the `specifications` repo hanging out among the dozens I have on GitHub.

Even though it would result in a little redundancy in the repo URL, I propose we rename this repo to `swift-logging-specifications`.

In the long-run, that'll make it easier to deal with forks and copies on the filesystem.

**Comment by akolov** [comment]
This is a good idea. Done and thanks!
